version: '1'
services:
  api:
    container_name: JDBC
    hostname: jdbc
    environment:
      - DB_USERNAME=$DB_USERNAME
      - DB_PASSWORD=$DB_PASSWORD
      - DB_HOST=$DB_HOST
      - DB_NAME=$DB_NAME
    ports:
      - "8080:8080"
    image: kainos-engacademy:jdbc